name: Scheduled scraping of NordVPN's API

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        * * * * *
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Scrape NordVPN's OpenVPN availability from API
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/checkout
      - id: foo
        uses: urishx/curl-then-jq-shell-action@v1.2.1
        with:
          who-to-greet: 'UriSh'
      - name: push
        uses: actions-x/commit@v6
        # https://github.com/actions-x/commit
        with:
          branch: db
          files: countries.tsv server-groups.tsv group-countries.tsv
          force: true
