on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: urishx/curl-then-jq-shell-action@v1.1.0
        with:
          who-to-greet: 'Mona the Octocat'
      - name: push
        uses: actions-x/commit@v2
        with:
          branch: db
          files: countries.tsv server-groups.tsv dump.json
          force: true
